spring:

  mvc:    format:      date: iso

  datasource:
    url: jdbc:h2:mem:product-service;DB_CLOSE_DELAY=-1

  jpa:    hibernate:      ddl-auto: none      use-new-id-generator-mappings: false
  flyway:    url: ${spring.datasource.url}
    user: sa
#    enabled: false